### ISSUE TITLE
CentOS Stream 9 tracker

### ISSUE THREAD

**Issue by cgwalters** [openshift/os#604]
Git branch: [c9s](https://github.com/openshift/os/tree/c9s)

## Latest release image

 `registry.ci.openshift.org/coreos/openshift49rhcos9@sha256:ca9a20ac916ce1a493339f1d99e80759a9cf5c7c1cf3ca5db8ff6b05c7e55ee8`

Status: boots and installs, but with some workarounds and patches

### Key bugs: 

C9S tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1988161

 - [ ] Control plane boots, but SDN fails to start  https://bugzilla.redhat.com/show_bug.cgi?id=1988520 (patched image `registry.ci.openshift.org/coreos/cluster-network-operator-c9s:latest`)
 - [ ] openvswitch SELinux https://bugzilla.redhat.com/show_bug.cgi?id=1988164 ([workaround: setenforce 0](https://github.com/openshift/os/commit/055b3e0ef0978d830876b6114d56514b41a34f57))
 - [ ] Some kola tests are failing (blocking https://github.com/openshift/release/pull/20804) e.g. https://github.com/openshift/os/issues/605 (https://bugzilla.redhat.com/show_bug.cgi?id=1989321)
 - [ ] Also disabled Secure Boot testing

### Test runs

- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1422286338022969344 (workers didn't come up, cause unknown)
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1422305043473764352 (same, no workers)

#### How to work on this

It's really the same as hacking on the main branch.  You can use `cosa build` and `kola` etc. locally.

Here's a sample command used to generate the current release image (manually): `oc adm release new --from-release registry.ci.openshift.org/ocp/release:4.9.0-0.nightly-2021-08-02-044755 machine-os-content=registry.ci.openshift.org/coreos/c9s-coreos:49.90.202107301731-0 cluster-network-operator=registry.ci.openshift.org/coreos/cluster-network-operator-c9s:latest --to-image registry.ci.openshift.org/coreos/openshift49rhcos9`

**Comment by cgwalters** [comment]
OK, the latest image gets farther from me, next failure is an `openshift-kube-apiserver` pod stuck in `Terminating` with the last event being `Warning  Failed          35m   kubelet  Error: cannot find volume "kubelet-dir" to mount into container "installer"`.  I don't see a pod in `crictl ps` corresponding to this, so I think it's a kubelet issue.

**Comment by miabbott** [comment]
Saw the SELinux check was failing in `misc-ro` on https://github.com/openshift/release/pull/20804

Pushed https://github.com/openshift/os/commit/c4208b3928533dc1f9a166987ae817225a4827a8
